package:
    name:           yii2-asset-autosize
    namespace:      hiqdev\assets\autosize
    title:          Yii 2 asset for bower autosize
    type:           yii2-extension
    keywords:       autosize, asset, extension, yii2
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
