parent:
    github:         hiqdev/hidev-config

package:
    name:           yii2-asset-autosize
    namespace:      hiqdev\assets\autosize
    title:          Yii 2 asset for bower autosize
    type:           yii2-extension
    keywords:       autosize, asset, extension, yii2
    year:           2015

composer.json:
    require:
        yiisoft/yii2:               "~2.0"
        bower-asset/autosize:       "3.0.6"
    extra:
        asset-installer-paths:
            npm-asset-library:      vendor/npm
            bower-asset-library:    vendor/bower

