package:
    type:           yii2-extension
    name:           yii2-asset-autosize
    title:          Yii2 asset for bower autosize
    headline:       Yii2 Autosize
    keywords:       autosize, asset, extension, yii2
    namespace:      hiqdev\assets\autosize
    description:    Yii2 asset for https://github.com/jackmoore/autosize

require:
    hiqdev/hidev-php:       "*"
    hiqdev/hidev-vendor:    "*"
